name: Update Sitemap URLs

on:
  workflow_dispatch:

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace old blog URLs with new URLs
        run: |
          sed -i 's|https://viktoria-az.store/bloq10.html|https://viktoria-az.store/paltarlarin-evde-renglenmesi|g' main/sitemap.xml
          sed -i 's|https://viktoria-az.store/bloq9.html|https://viktoria-az.store/qara-sinka-paltar-uchun|g' main/sitemap.xml
          sed -i 's|https://viktoria-az.store/bloq8.html|https://viktoria-az.store/geyim-ve-tekstil-boyasi|g' main/sitemap.xml
          sed -i 's|https://viktoria-az.store/bloq7.html|https://viktoria-az.store/paltar-boyasi-hardan-almaq-olar|g' main/sitemap.xml
          sed -i 's|https://viktoria-az.store/bloq6.html|https://viktoria-az.store/paltar-boyasi-online-sifaris|g' main/sitemap.xml
          sed -i 's|https://viktoria-az.store/bloq5.html|https://viktoria-az.store/boyanin-istifade-qaydalari|g' main/sitemap.xml
          sed -i 's|https://viktoria-az.store/bloq4.html|https://viktoria-az.store/qaliciliga-tesir-eden-amiller|g' main/sitemap.xml
          sed -i 's|https://viktoria-az.store/bloq3.html|https://viktoria-az.store/sabitlesdirici-nece-istifade-olunur|g' main/sitemap.xml
          sed -i 's|https://viktoria-az.store/bloq2.html|https://viktoria-az.store/paltaryuyan-masinda-istifade-qaydalari|g' main/sitemap.xml
          sed -i 's|https://viktoria-az.store/bloq1.html|https://viktoria-az.store/qabda-boyama-telimati|g' main/sitemap.xml

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add main/sitemap.xml
          git commit -m "Update sitemap blog URLs" || echo "No changes to commit"
          git push
